### ISSUE TITLE
iOS 13.4.1 -> iOS 13.5.1 iPhone X

### ISSUE THREAD

**Issue by Lunascaped** [ddvniele/iOS-64bit-dualboot-guide#4]
Hello, I am slightly confused by the wording in this document. Using this guide am I able to go from iOS 13.4.1 to iOS 13.5.1 on a iPhone X? Just confused about the SEP part.

**Comment by ddvniele** [comment]
you should be able to do that. usually the sep part suppose that you are on the newest iOS possible. but iOS 13.4.1 and iOS 13.5.1 sep is the same so you shouldn't have any problem
